### ISSUE TITLE
Issue with Alfred 4

### ISSUE THREAD

**Issue by TheOutdoorProgrammer** [juju4/ansible-macos-apps-install#3]
When I install alfred 4 via:
`{u: "https://cachefly.alfredapp.com/Alfred_4.6_1266.dmg", f: "alfred.dmg", n: "Alfred 4"}`

It sits for like 10 minutes on `TASK [juju4.macos-apps-install : Copy 'Alfred 4' app to '/Applications']` even though the file is very small.

Eventually it does get past that step and says its changed, but the application looks like this in /Applications:
![image](https://user-images.githubusercontent.com/13936290/138387288-a3aa4798-c64b-443d-b430-a008a8633bbf.jpeg)

What am I doing wrong? Sorry for formatting, Im on my mobile device.

**Comment by Apollorion** [comment]
Also, when I try to open the application it says I dont have permission to do so.

drwxr-xr-x, its owned by me with the group `admin`.

**Comment by juju4** [comment]
f is optional. default to url basename per https://github.com/juju4/ansible-macos-apps-install/blob/master/tasks/darwin.yml#L40 (but somewhat not a filename or extra query strings)
n is the app_name which is used for copy per https://github.com/juju4/ansible-macos-apps-install/blob/master/tasks/archive-install.yml#L69 with default mode 644. for permission check, 755 should be good enough, 777 changes nothing from a read/execution permissions, only write permissions for user group and others.
to is needed for existence check/idempotence.

I found some condition issue in HEAD branch, not sure which version/commit of the role you are using.
Fixed in latest HEAD

From testing in github action
https://github.com/juju4/ansible-macos-apps-install/runs/3986477946?check_suite_focus=true#step:10:733
```
12896385199        0 drwxr-xr-x    3 root             admin                  96 Oct 24 00:30 /Applications/Alfred 4.app
12896385200        0 drwxr-xr-x   10 root             admin                 320 Oct 24 00:35 /Applications/Alfred 4.app/Contents
 12896392213        0 drwxr-xr-x    3 root             admin                  96 Oct 24 00:35 /Applications/Alfred 4.app/Contents/MacOS
12896392208      848 -rw-r--r--    1 root             wheel              434128 Oct 24 00:35 /Applications/Alfred 4.app/Contents/MacOS/Alfred
```

Initially, mode was a single definition as input to ansible but seems a preserve option has been added.
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html#parameter-mode
switched to that

all good after that
https://github.com/juju4/ansible-macos-apps-install/runs/3986577625?check_suite_focus=true#step:10:773
```
12896390407        0 drwxr-xr-x    3 root             admin                  96 Oct 24 01:03 /Applications/Alfred 4.app/Contents/MacOS
12896390398      848 -rwxr-xr-x    1 root             wheel              434128 Oct 24 01:02 /Applications/Alfred 4.app/Contents/MacOS/Alfred
```

Please try latest HEAD and confirm ok
